Mounting Drive

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Requesting Git token

In [30]:
from getpass import getpass

token = getpass("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")

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··········

https://github.com/

In [31]:
!git clone https://{token}@github.com/LulutheBA/ANLOK-WATER-PREDICTION-PROJECT-.git

fatal: destination path 'ANLOK-WATER-PREDICTION-PROJECT-' already exists and is not an empty directory.

verify

In [32]:
import os

os.listdir("/content/ANLOK-WATER-PREDICTION-PROJECT-")

['.git', 'Raw', 'Training']

Clone GitHub Repository

In [33]:
!git clone https://github.com/LulutheBA/ANLOK-WATER-PREDICTION-PROJECT-.git

fatal: destination path 'ANLOK-WATER-PREDICTION-PROJECT-' already exists and is not an empty directory.

Check the project structure

In [34]:
import pandas as pd
import os
import glob

Find all datasets automatically

In [36]:
repo_path = "/content/ANLOK-WATER-PREDICTION-PROJECT-"

csv_files = glob.glob(
    repo_path + "/**/*.csv",
    recursive=True
)

len(csv_files)

27

Display Datasets

In [37]:
for file in csv_files:
    print(file)

/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Vulnerability/Vulnerability Score Per leg_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Vulnerability/Areas of Highest Vulnerability_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Weather/4355517.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Economics/Residential Tariffs_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Demand/Water demand growth_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Social Impact/Protests Identified by Municipal IQ_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Quality/Operational_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Quality/NIWIS_RWT_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Quality/Microbiological _ Acute Health_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Quality/NIWIS_WasteWaterQuality_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Quality/Institutional Compliance_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Quality/Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30].csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Quality/NIWIS_GroundwaterStatus_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Infrastructure/Source of Water Households _ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Infrastructure/Households Served with Water_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Infrastructure/Surface Water Storage (2014-2020).csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Infrastructure/People Served with Water_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Infrastructure/Surface Water Storage ( 2020 -2026).csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Infrastructure/NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Infrastructure/NIWIS_Water Supply Reliability - population_16-Jul-2026 .csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Infrastructure/Piped Water Households _ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Infrastructure/Potable Systems_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Water Infrastructure/Verified - River Flow ( National ).csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Population&Demographics/Timeseries Households_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Population&Demographics/TimeSeries Population_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Population&Demographics/Total Households_ 2026_04_21.csv
/content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Population&Demographics/Total Population_ 2026_04_21.csv

Dictionary of all the CSV files

In [38]:
import pandas as pd
import os

datasets = {}

for file in csv_files:
    name = os.path.basename(file).replace(".csv","")
    try:
        datasets[name] = pd.read_csv(file)
    except pd.errors.EmptyDataError:
        print(f"Skipping empty or malformed file: {file}")
        continue # Skip to the next file

print(datasets.keys())

Skipping empty or malformed file: /content/ANLOK-WATER-PREDICTION-PROJECT-/Raw/Weather/4355517.csv
dict_keys(['Vulnerability Score Per leg_ 2026_04_21', 'Areas of Highest Vulnerability_ 2026_04_21', 'Residential Tariffs_ 2026_04_21', 'Water demand growth_ 2026_04_21', 'Protests Identified by Municipal IQ_ 2026_04_21', 'Operational_ 2026_04_21', 'NIWIS_RWT_16-Jul-2026 ', 'Microbiological _ Acute Health_ 2026_04_21', 'NIWIS_WasteWaterQuality_16-Jul-2026 ', 'Institutional Compliance_ 2026_04_21', 'Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]', 'NIWIS_GroundwaterStatus_16-Jul-2026 ', 'Source of Water Households _ 2026_04_21', 'Households Served with Water_ 2026_04_21', 'Surface Water Storage (2014-2020)', 'People Served with Water_ 2026_04_21', 'Surface Water Storage ( 2020 -2026)', 'NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026 ', 'NIWIS_Water Supply Reliability - population_16-Jul-2026 ', 'Piped Water Households _ 2026_04_21', 'Potable Systems_ 2026_04_21', 'Verified - River Flow ( National )', 'Timeseries Households_ 2026_04_21', 'TimeSeries Population_ 2026_04_21', 'Total Households_ 2026_04_21', 'Total Population_ 2026_04_21'])

inventory

In [21]:
inventory = []

for category, df in datasets.items():

    inventory.append({

            "Category": category,
            "Dataset": category,
            "Rows": df.shape[0],
            "Columns": df.shape[1],
            "Missing Values": df.isnull().sum().sum(),
            "Duplicate Rows": df.duplicated().sum()

        })

inventory_df = pd.DataFrame(inventory)

inventory_df

,Category,Dataset,Rows,Columns,Missing Values,Duplicate Rows
0,Vulnerability Score Per leg_ 2026_04_21,Vulnerability Score Per leg_ 2026_04_21,11,9,17,0
1,Areas of Highest Vulnerability_ 2026_04_21,Areas of Highest Vulnerability_ 2026_04_21,11,21,29,0
2,Residential Tariffs_ 2026_04_21,Residential Tariffs_ 2026_04_21,11,7,15,0
3,Water demand growth_ 2026_04_21,Water demand growth_ 2026_04_21,11,10,18,0
4,Protests Identified by Municipal IQ_ 2026_04_21,Protests Identified by Municipal IQ_ 2026_04_21,11,16,24,0
5,Operational_ 2026_04_21,Operational_ 2026_04_21,11,8,16,0
6,NIWIS_RWT_16-Jul-2026,NIWIS_RWT_16-Jul-2026,9,5,0,0
7,Microbiological _ Acute Health_ 2026_04_21,Microbiological _ Acute Health_ 2026_04_21,11,8,16,0
8,NIWIS_WasteWaterQuality_16-Jul-2026,NIWIS_WasteWaterQuality_16-Jul-2026,143,6,143,0
9,Institutional Compliance_ 2026_04_21,Institutional Compliance_ 2026_04_21,11,5,13,0
10,Drinking Water Quality Compliance - SANS 241 _...,Drinking Water Quality Compliance - SANS 241 _...,4,2,0,0
11,NIWIS_GroundwaterStatus_16-Jul-2026,NIWIS_GroundwaterStatus_16-Jul-2026,1947,8,2511,1
12,Source of Water Households _ 2026_04_21,Source of Water Households _ 2026_04_21,10,13,20,0
13,Households Served with Water_ 2026_04_21,Households Served with Water_ 2026_04_21,11,17,25,0
14,Surface Water Storage (2014-2020),Surface Water Storage (2014-2020),374,9,1971,0
15,People Served with Water_ 2026_04_21,People Served with Water_ 2026_04_21,11,17,25,0
16,Surface Water Storage ( 2020 -2026),Surface Water Storage ( 2020 -2026),375,9,1953,0
17,NIWIS_Access to Water Infrastructure Delivered...,NIWIS_Access to Water Infrastructure Delivered...,0,4,0,0
18,NIWIS_Water Supply Reliability - population_16...,NIWIS_Water Supply Reliability - population_16...,144,14,189,0
19,Piped Water Households _ 2026_04_21,Piped Water Households _ 2026_04_21,10,12,19,0
20,Potable Systems_ 2026_04_21,Potable Systems_ 2026_04_21,61,11,69,0
21,Verified - River Flow ( National ),Verified - River Flow ( National ),7,2,0,0
22,Timeseries Households_ 2026_04_21,Timeseries Households_ 2026_04_21,11,35,43,0
23,TimeSeries Population_ 2026_04_21,TimeSeries Population_ 2026_04_21,11,35,43,0
24,Total Households_ 2026_04_21,Total Households_ 2026_04_21,11,8,16,0
25,Total Population_ 2026_04_21,Total Population_ 2026_04_21,11,8,16,0

Save inventory

In [22]:
inventory_df.to_csv(
    "ANLOK_dataset_inventory.csv",
    index=False
)

Inspect dataset columns

In [39]:
for category, df in datasets.items():

    print("\n======================")
    print(category)

    print(df.columns.tolist())

======================
Vulnerability Score Per leg_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', '1# Water Services Planning', '4# Technical Staff Capacity (Numbers)', '6# Water Conservation & Water Demand Management (WC/WDM)', '7# Drinking Water Safety & Regulatory Compliance', '10# Infrastructure Asset Management (IAM)', '11# Operation & Maintenance (O&M) of Assets']

======================
Areas of Highest Vulnerability_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', '1# Water Services Planning', '2# Management Skill Level (Technical)', '3# Staff Skill Level (Technical)', '4# Technical Staff Capacity (Numbers)', '5# Water Resource Management (WRM)', '6# Water Conservation & Water Demand Management (WC/WDM)', '7# Drinking Water Safety & Regulatory Compliance', '8# Basic Sanitation', '9# Wastewater/Environmental Safety & Regulatory Compliance', '10# Infrastructure Asset Management (IAM)', '11# Operation & Maintenance (O&M) of Assets', '12# Financial Management', '13# Revenue Collection', '14# Financial Asset Management', '15# Information Management (IT)', '16# Organisational Performance Monitoring', '17# Water and Sanitation Service Quality', '18# Customer Care (CRM)']

======================
Residential Tariffs_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'Tariff 0-6kl (incl#VAT)', 'Tariff 6-20kl (incl#VAT)', 'Tariff 20-60kl (incl#VAT)', 'Tariff >60kl (incl#VAT)']

======================
Water demand growth_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', '% Water Demand Growth', '% Non-Revenue Water', '% Water Losses', 'System input volume (litres)', 'Revenue water (litres)', 'Non-Revenue water (litres)', 'Water Losses (litres)']

======================
Protests Identified by Municipal IQ_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'Total Protests', 'Informal', 'Violent', 'Xenophobia', 'Criminality', 'Corruption', 'Councillor', 'Water', 'Sanitation', 'Electricity', 'Refuse Removal', 'Roads', 'Housing']

======================
Operational_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'Risk Type', 'Analysis Done', 'Analysis Failed', 'Compliance Percentage', 'Compliance Result']

======================
NIWIS_RWT_16-Jul-2026
['WMA', 'Date', 'Domestic and Industry c/m3', 'Irrigation c/m3', 'Forestry c/m3']

======================
Microbiological _ Acute Health_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'Risk Type', 'Analysis Done', 'Analysis Failed', 'Compliance Percentage', 'Compliance Result']

======================
NIWIS_WasteWaterQuality_16-Jul-2026
['Unnamed: 0', 'WSA', 'Chemical', 'Microbiological', 'Physical', 'Monitoring']

======================
Institutional Compliance_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'Potable Water Compliance Percentage', 'Effluent Water Compliance Percentage']

======================
Drinking Water Quality Compliance - SANS 241 _2006 - National [From_ 2022-07-01 To_ 2026-06-30]
["'Category", "'SANS 241 :2006:"]

======================
NIWIS_GroundwaterStatus_16-Jul-2026
['Quaternary', 'Reserve Study', 'Available (GRA2)(m3/a)', 'Recharge (GWR)(m3/a)', 'Reserve (GWR)(m3/a)', 'Abstracted (WARMS)(m3/a)', 'Surplus (GRA2)(m3/a)', 'Surplus (GWR)(m3/a)']

======================
Source of Water Households _ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'Regional/local water scheme (operated by municipality or other w', 'Borehole', 'Spring', 'Rain water tank', 'Dam/pool/stagnant water', 'River/stream', 'Water vendor', 'Water tanker', 'Other', 'Not applicable']

======================
Households Served with Water_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'Households served with water 1994 to April 2025', 'Households served with water 201415', 'Households served with water 201516', 'Households served with water 201617', 'Households served with water 201718', 'Households served with water 201819', 'Households served with water 201920', 'Households served with water 202021', 'Households served with water 202122', 'Households served with water 202223', 'Households served with water 202324', 'Households served with water 202425', 'Households served with water 202526', 'Planned Households to be served 202627']

======================
Surface Water Storage (2014-2020)
["'DateTime", "'High", "'Moderately High", "'Normal", "'Moderately Low", "'Low", "'Very Low", "'2018/2019", "'2019/2020"]

======================
People Served with Water_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'Population served with water 1994 to April 2025', 'Population served with water 201415', 'Population served with water 201516', 'Population served with water 201617', 'Population served with water 201718', 'Population served with water 201819', 'Population served with water 201920', 'Population served with water 202021', 'Population served with water 202122', 'Population served with water 202223', 'Population served with water 202324', 'Population served with water 202425', 'Population served with water 202526', 'Planned Population to be served 202627']

======================
Surface Water Storage ( 2020 -2026)
["'DateTime", "'High", "'Moderately High", "'Normal", "'Moderately Low", "'Low", "'Very Low", "'2024/2025", "'2025/2026"]

======================
NIWIS_Access to Water Infrastructure Delivered- Population_16-Jul-2026
['WSA', 'Population', 'Population with access', '%Population  with access']

======================
NIWIS_Water Supply Reliability - population_16-Jul-2026
['Unnamed: 0', 'WSA Name', 'population', 'population with access  to water', 'population Reliable Supply', '% population Reliable Supply', 'Urban population', 'Urban population with access to water', 'Urban population Reliable Supply', '% Urban population Reliable Supply', 'Rural population', 'Rural population  with access  to water', 'Rural population Reliable Supply', '% Rural population Reliable Supply']

======================
Piped Water Households _ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'Piped (tap) water inside dwelling/institution', 'Piped (tap) water inside yard', 'Piped (tap) water on community stand: distance less than 200m fr', 'Piped (tap) water on community stand: distance between 200m and ', 'Piped (tap) water on community stand: distance between 500m and ', 'Piped (tap) water on community stand: distance greater than 1000', 'No access to piped (tap) water', 'Unspecified', 'Not applicable']

======================
Potable Systems_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'System name', 'System area', 'Population in system', 'Households in System', 'Households with Access to RDP Water', 'Households with Access to Reliable Water', 'Drinking Water Quality Percentage', 'Latest Blue Drop Score']

======================
Verified - River Flow ( National )
["'Flow", "'Flow Level :"]

======================
Timeseries Households_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'April 1994', 'April 1995', 'April 1996', 'April 1997', 'April 1998', 'April 1999', 'April 2000', 'April 2001', 'April 2002', 'April 2004', 'April 2005', 'April 2006', 'April 2007', 'April 2008', 'April 2009', 'April 2010', 'April 2011', 'April 2012', 'April 2013', 'April 2014', 'April 2015', 'April 2016', 'April 2017', 'April 2018', 'April 2019', 'April 2020', 'April 2021', 'April 2022', 'April 2023', 'April 2024', 'April 2025', 'April 2026']

======================
TimeSeries Population_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'April 1994', 'April 1995', 'April 1996', 'April 1997', 'April 1998', 'April 1999', 'April 2000', 'April 2001', 'April 2002', 'April 2004', 'April 2005', 'April 2006', 'April 2007', 'April 2008', 'April 2009', 'April 2010', 'April 2011', 'April 2012', 'April 2013', 'April 2014', 'April 2015', 'April 2016', 'April 2017', 'April 2018', 'April 2019', 'April 2020', 'April 2021', 'April 2022', 'April 2023', 'April 2024', 'April 2025', 'April 2026']

======================
Total Households_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'Total Households', 'Total Population', 'HH Density', 'Urban Households', 'Rural Households']

======================
Total Population_ 2026_04_21
['Region', 'Time Frame', 'Unnamed: 2', 'Total Population', 'Total Households', 'HH Density', 'Urban Population', 'Rural Population']

Access any Dataset

In [29]:
datasets["Total Households_ 2026_04_21"].head()

,Region,Time Frame,Unnamed: 2,Total Households,Total Population,HH Density,Urban Households,Rural Households
0,City of Johannesburg Metropolitan Municipality,April 2026,NaN,1 999 327,5 045 624,2.52,1 908 922,90 405
1,City of Tshwane Metropolitan Municipality,April 2026,NaN,1 469 057,4 426 868,3.01,1 320 442,148 615
2,Ekurhuleni Metropolitan Municipality,April 2026,NaN,1 567 566,4 391 840,2.80,1 369 578,197 988
3,Emfuleni,April 2026,NaN,326 534,1 025 702,3.14,302 095,24 439
4,Lesedi,April 2026,NaN,47 233,144 504,3.06,39 418,7 815